### ISSUE TITLE
[BUG] KeyError: "1 required columns are missing from the provided dataset to transform using CategoryFeatureGenerator. Missing columns: ['Product_Description']"

### ISSUE THREAD

**Issue by yaoruinupt** [autogluon/autogluon#2688]
[please refer to my colab file to see the bug in details:
https://colab.research.google.com/drive/1IbQeeavwM7wNSghw0B2kWBsE-RHHHUMU?usp=sharing]
======================================================================
Bug description:

I am refering multimal tutorials to train a dataset with only text features.(refering page: https://auto.gluon.ai/stable/tutorials/tabular_prediction/tabular-multimodal-text-others.html)

here are my settings:
from autogluon.tabular import TabularPredictor
predictor = TabularPredictor(label='Sentiment', path='./model',problem_type='multiclass',eval_metric="f1_micro",verbosity=4)
predictor.fit(train_df,hyperparameters='multimodal', time_limit=None,presets=['best_quality'],auto_stack=True,refit_full=True,set_best_to_refit_full=True,keep_only_best=True,save_space=True,num_bag_sets=1, num_gpus=1)

While training is going well, it seems that testing meets bugs:
KeyError: "1 required columns are missing from the provided dataset to transform using CategoryFeatureGenerator. Missing columns: ['Product_Description']"
here ['Product_Description']" is the feature of testing set. However, I promise the testing set include this feature.

Can anyone give a hand?

**Comment by yaoruinupt** [comment]
Besides, this bug also seems strange:

Fitting model: TextPredictor_BAG_L1 ...
	Dropped 262 of 263 features.
	Warning: Exception caused TextPredictor_BAG_L1 to fail during training... Skipping this model.
		module 'PIL.Image' has no attribute 'Resampling'

how can PIL.Image influence TextPredictor...

**Comment by Innixma** [comment]
Thanks for providing the notebook, this helped immensely!

I was able to reproduce the error and it is fixed in #2705 and will be part of v0.7 release.

A workaround for impacted releases v0.6.2 & v0.6.1: Either 1. downgrade to v0.6.0 or 2. include extra non-text features alongside the text features. For example, using `feature_columns = ['Product_Description', 'Product_Type']` will avoid the error in your example.

**Comment by Innixma** [comment]
> Besides, this bug also seems strange:
> 
> Fitting model: TextPredictor_BAG_L1 ... Dropped 262 of 263 features. Warning: Exception caused TextPredictor_BAG_L1 to fail during training... Skipping this model. module 'PIL.Image' has no attribute 'Resampling'
> 
> how can PIL.Image influence TextPredictor...

This appears to be a separate bug. Probably caused by #2519, related to PIL version. It is unclear why our CI runs succeed but Colab is failing.

The bug can be simplified to the following:

```python3
import autogluon.multimodal
```

->

```
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

Here is a notebook reproducing: https://colab.research.google.com/drive/1f3hxVNjzdJz6dzleOBsO7nL5c6Z8L6mr?usp=sharing

In your notebook it appears that TextPredictor succeeded training after you updated the PIL version.

```
Fitting model: TextPredictor_BAG_L1 ...
	Dropped 262 of 263 features.
	Dropped 0 of 263 features.
	Fitting TextPredictor_BAG_L1 with 'num_gpus': 1, 'num_cpus': 2
Saving ./model/models/TextPredictor_BAG_L1/utils/model_template.pkl
Loading: ./model/models/TextPredictor_BAG_L1/utils/model_template.pkl
Upper level total_num_cpus, num_gpus 2 | 1
	Dropped 262 of 263 features.
minimum_model_resources: {'num_cpus': 1, 'num_gpus': 1}
user_cpu_per_job, user_gpu_per_job None | None
user_ensemble_cpu, user_ensemble_gpu None | None
Resources info for GpuResourceCalculator: {'resources_per_job': {'cpu': 2, 'gpu': 1.0}, 'num_parallel_jobs': 1, 'batches': 8, 'cpu_per_job': 2, 'gpu_per_job': 1.0}
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Folding resources per job {'num_gpus': 1.0, 'num_cpus': 2}
Saving ./model/models/TextPredictor_BAG_L1/utils/oof.pkl
Saving ./model/models/TextPredictor_BAG_L1/model.pkl
	0.7	 = Validation score   (f1_micro)
	1584.25s	 = Training   runtime
	6.03s	 = Validation runtime
```

**Comment by Innixma** [comment]
Created new issue for the PIL error: #2707

**Comment by Innixma** [comment]
Regarding the PIL issue, the solution is to restart the colab runtime after installing AutoGluon. Colab starts with an old version of PIL that leads to bugs if the environment is not restarted.

**Comment by yaoruinupt** [comment]
> Thanks for providing the notebook, this helped immensely!
> 
> I was able to reproduce the error and it is fixed in #2705 and will be part of v0.7 release.
> 
> A workaround for impacted releases v0.6.2 & v0.6.1: Either 1. downgrade to v0.6.0 or 2. include extra non-text features alongside the text features. For example, using `feature_columns = ['Product_Description', 'Product_Type']` will avoid the error in your example.

Many thanks for your kind reply and help!
